import { Course, Module } from './types';

export const CATEGORIES = [
  "Development",
  "Design",
  "Business",
  "Data Science",
  "Marketing",
  "Photography"
];

const generateCourses = (): Course[] => [
  {
    id: '1',
    title: 'Advanced React Patterns',
    description: 'Master modern React with hooks, context, and performance optimization techniques.',
    instructor: 'Sarah Drasner',
    thumbnailUrl: 'https://picsum.photos/seed/react1/800/450',
    category: 'Development',
    tags: ['React', 'Frontend'],
    difficulty: 'Advanced',
    lessons: 42,
    duration: '12h 15m',
    rating: 4.9,
    reviewCount: 1250,
    price: 99,
    isPopular: true,
    enrollmentCount: 15400,
    accessType: 'Paid',
    updatedAt: '2024-03-10'
  },
  {
    id: '2',
    title: 'UI/UX Design Masterclass',
    description: 'Learn to design beautiful interfaces and user experiences from scratch using Figma.',
    instructor: 'Gary Simon',
    thumbnailUrl: 'https://picsum.photos/seed/design1/800/450',
    category: 'Design',
    tags: ['Figma', 'UI Design'],
    difficulty: 'Beginner',
    lessons: 65,
    duration: '18h 30m',
    rating: 4.8,
    reviewCount: 3400,
    price: 0,
    isPopular: true,
    enrollmentCount: 45000,
    accessType: 'Open',
    updatedAt: '2024-02-15'
  },
  {
    id: '3',
    title: 'Python for Data Science',
    description: 'Go from zero to hero in Python. Learn Pandas, NumPy, Matplotlib and basic Machine Learning.',
    instructor: 'Jose Portilla',
    thumbnailUrl: 'https://picsum.photos/seed/data1/800/450',
    category: 'Data Science',
    tags: ['Python', 'Data'],
    difficulty: 'Intermediate',
    lessons: 110,
    duration: '24h',
    rating: 4.7,
    reviewCount: 8900,
    price: 19,
    isNew: true,
    enrollmentCount: 8900,
    accessType: 'Paid',
    updatedAt: '2024-04-01'
  },
  {
    id: '4',
    title: 'Digital Marketing 2024',
    description: 'Comprehensive guide to SEO, Social Media Marketing, and Email Marketing strategies.',
    instructor: 'Neil Patel',
    thumbnailUrl: 'https://picsum.photos/seed/market1/800/450',
    category: 'Marketing',
    tags: ['SEO', 'Marketing'],
    difficulty: 'Beginner',
    lessons: 30,
    duration: '8h 45m',
    rating: 4.6,
    reviewCount: 560,
    price: 49,
    enrollmentCount: 3200,
    accessType: 'Paid',
    updatedAt: '2024-01-20'
  },
  {
    id: '5',
    title: 'Product Management',
    description: 'Learn the core skills required to become a successful Product Manager in tech.',
    instructor: 'Lenny Rachitsky',
    thumbnailUrl: 'https://picsum.photos/seed/prod1/800/450',
    category: 'Business',
    tags: ['Product', 'Agile'],
    difficulty: 'Intermediate',
    lessons: 25,
    duration: '6h 15m',
    rating: 4.9,
    reviewCount: 210,
    price: 0,
    isPopular: false,
    enrollmentCount: 1500,
    accessType: 'Invite-only',
    updatedAt: '2024-03-25'
  },
  {
    id: '6',
    title: 'Node.js Microservices',
    description: 'Build scalable backend systems using Node.js, Docker, and Kubernetes.',
    instructor: 'Andrew Mead',
    thumbnailUrl: 'https://picsum.photos/seed/node1/800/450',
    category: 'Development',
    tags: ['Node.js', 'Backend'],
    difficulty: 'Advanced',
    lessons: 85,
    duration: '32h',
    rating: 4.7,
    reviewCount: 4500,
    price: 89,
    enrollmentCount: 12000,
    accessType: 'Paid',
    updatedAt: '2023-12-10'
  },
  {
    id: '7',
    title: 'Photography Essentials',
    description: 'Understand aperture, shutter speed, ISO, and composition to take stunning photos.',
    instructor: 'Phil Ebiner',
    thumbnailUrl: 'https://picsum.photos/seed/photo1/800/450',
    category: 'Photography',
    tags: ['Camera', 'Art'],
    difficulty: 'Beginner',
    lessons: 50,
    duration: '14h 20m',
    rating: 4.8,
    reviewCount: 6700,
    price: 29,
    enrollmentCount: 28000,
    accessType: 'Paid',
    updatedAt: '2024-02-28'
  },
  {
    id: '8',
    title: 'Machine Learning A-Z',
    description: 'Hands-on Python & R In Data Science to create Machine Learning Models.',
    instructor: 'Kirill Eremenko',
    thumbnailUrl: 'https://picsum.photos/seed/ml1/800/450',
    category: 'Data Science',
    tags: ['AI', 'Python'],
    difficulty: 'Advanced',
    lessons: 200,
    duration: '44h',
    rating: 4.5,
    reviewCount: 15000,
    price: 129,
    isPopular: true,
    enrollmentCount: 150000,
    accessType: 'Paid',
    updatedAt: '2023-11-15'
  },
  {
    id: '9',
    title: 'Vue.js 3 Fundamentals',
    description: 'The complete guide to Vue.js 3. Build typical SPAs with the Composition API.',
    instructor: 'Maximilian',
    thumbnailUrl: 'https://picsum.photos/seed/vue1/800/450',
    category: 'Development',
    tags: ['Vue', 'Frontend'],
    difficulty: 'Beginner',
    lessons: 40,
    duration: '10h',
    rating: 4.8,
    reviewCount: 2200,
    price: 15,
    isNew: true,
    enrollmentCount: 5000,
    accessType: 'Paid',
    updatedAt: '2024-04-10'
  },
  {
    id: '10',
    title: 'Cinema 4D Masterclass',
    description: 'Create stunning 3D motion graphics and visual effects.',
    instructor: 'Motion Design School',
    thumbnailUrl: 'https://picsum.photos/seed/3d1/800/450',
    category: 'Design',
    tags: ['3D', 'Motion'],
    difficulty: 'Advanced',
    lessons: 120,
    duration: '40h',
    rating: 4.9,
    reviewCount: 1100,
    price: 199,
    enrollmentCount: 2000,
    accessType: 'Paid',
    updatedAt: '2024-01-05'
  },
  {
    id: '11',
    title: 'MBA in a Box',
    description: 'Business strategy, management, and leadership skills for entrepreneurs.',
    instructor: 'Chris Haroun',
    thumbnailUrl: 'https://picsum.photos/seed/business1/800/450',
    category: 'Business',
    tags: ['MBA', 'Strategy'],
    difficulty: 'Beginner',
    lessons: 90,
    duration: '22h',
    rating: 4.6,
    reviewCount: 8900,
    price: 14,
    enrollmentCount: 56000,
    accessType: 'Paid',
    updatedAt: '2023-10-10'
  },
  {
    id: '12',
    title: 'Deep Learning Specialization',
    description: 'Master Neural Networks and Deep Learning with TensorFlow.',
    instructor: 'Andrew Ng',
    thumbnailUrl: 'https://picsum.photos/seed/deep1/800/450',
    category: 'Data Science',
    tags: ['AI', 'Deep Learning'],
    difficulty: 'Advanced',
    lessons: 150,
    duration: '60h',
    rating: 4.9,
    reviewCount: 25000,
    price: 79,
    enrollmentCount: 100000,
    accessType: 'Paid',
    updatedAt: '2023-09-01'
  },
  {
    id: '13',
    title: 'Rust Programming',
    description: 'Systems programming with Rust. Memory safety without garbage collection.',
    instructor: 'Tim Ruscica',
    thumbnailUrl: 'https://picsum.photos/seed/rust1/800/450',
    category: 'Development',
    tags: ['Rust', 'Backend'],
    difficulty: 'Intermediate',
    lessons: 45,
    duration: '15h',
    rating: 4.8,
    reviewCount: 1500,
    price: 39,
    isNew: true,
    enrollmentCount: 3000,
    accessType: 'Paid',
    updatedAt: '2024-04-12'
  },
   {
    id: '14',
    title: 'Copywriting Secrets',
    description: 'How to write copy that sells. Psychology of persuasion.',
    instructor: 'Jim Edwards',
    thumbnailUrl: 'https://picsum.photos/seed/copy1/800/450',
    category: 'Marketing',
    tags: ['Writing', 'Sales'],
    difficulty: 'Beginner',
    lessons: 20,
    duration: '5h',
    rating: 4.5,
    reviewCount: 3000,
    price: 29,
    enrollmentCount: 12000,
    accessType: 'Paid',
    updatedAt: '2024-01-15'
  },
  {
    id: '15',
    title: 'Blender 3D Modeling',
    description: 'Create game assets and characters with Blender.',
    instructor: 'GameDev.tv',
    thumbnailUrl: 'https://picsum.photos/seed/blender1/800/450',
    category: 'Design',
    tags: ['3D', 'Game Art'],
    difficulty: 'Intermediate',
    lessons: 80,
    duration: '25h',
    rating: 4.8,
    reviewCount: 6500,
    price: 19,
    enrollmentCount: 34000,
    accessType: 'Paid',
    updatedAt: '2024-02-10'
  },
  {
    id: '16',
    title: 'Mindfulness & Meditation',
    description: 'Reduce stress and anxiety through guided mindfulness practices.',
    instructor: 'Headspace',
    thumbnailUrl: 'https://picsum.photos/seed/mind1/800/450',
    category: 'Business',
    tags: ['Wellness', 'Health'],
    difficulty: 'Beginner',
    lessons: 15,
    duration: '4h',
    rating: 4.9,
    reviewCount: 10000,
    price: 0,
    isPopular: true,
    enrollmentCount: 200000,
    accessType: 'Open',
    updatedAt: '2024-05-01'
  },
  {
    id: '17',
    title: 'Financial Analysis 101',
    description: 'Learn to read financial statements and analyze company performance.',
    instructor: 'NYU Stern',
    thumbnailUrl: 'https://picsum.photos/seed/finance1/800/450',
    category: 'Business',
    tags: ['Finance', 'Analysis'],
    difficulty: 'Intermediate',
    lessons: 55,
    duration: '18h',
    rating: 4.7,
    reviewCount: 2300,
    price: 49,
    enrollmentCount: 8000,
    accessType: 'Paid',
    updatedAt: '2024-03-15'
  },
  {
    id: '18',
    title: 'Abstract Painting',
    description: 'Express yourself through abstract acrylic painting techniques.',
    instructor: 'MoMA',
    thumbnailUrl: 'https://picsum.photos/seed/art1/800/450',
    category: 'Design',
    tags: ['Art', 'Painting'],
    difficulty: 'Beginner',
    lessons: 22,
    duration: '6h',
    rating: 4.8,
    reviewCount: 450,
    price: 29,
    enrollmentCount: 1500,
    accessType: 'Paid',
    updatedAt: '2024-01-28'
  },
   {
    id: '19',
    title: 'Go Lang Fundamentals',
    description: 'Learn Go from Google. Efficient, reliable, and scalable software.',
    instructor: 'Google',
    thumbnailUrl: 'https://picsum.photos/seed/go1/800/450',
    category: 'Development',
    tags: ['Go', 'Backend'],
    difficulty: 'Intermediate',
    lessons: 60,
    duration: '20h',
    rating: 4.6,
    reviewCount: 1200,
    price: 0,
    enrollmentCount: 9000,
    accessType: 'Open',
    updatedAt: '2024-02-05'
  },
  {
    id: '20',
    title: 'Portrait Photography',
    description: 'Master lighting and posing for professional portraits.',
    instructor: 'Annie Leibovitz',
    thumbnailUrl: 'https://picsum.photos/seed/portrait1/800/450',
    category: 'Photography',
    tags: ['Portrait', 'Lighting'],
    difficulty: 'Advanced',
    lessons: 35,
    duration: '9h',
    rating: 4.9,
    reviewCount: 5600,
    price: 99,
    enrollmentCount: 18000,
    accessType: 'Paid',
    updatedAt: '2023-12-20'
  }
];

export const MOCK_COURSES = generateCourses();

export const MOCK_CURRICULUM: Module[] = [
    {
      id: 'm1',
      title: 'Module 1: Foundations',
      lessons: [
        {
          id: 'l1',
          title: 'Introduction to the Course',
          type: 'video',
          duration: '10:00',
          isCompleted: true,
          videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
        },
        {
          id: 'l2',
          title: 'Core Concepts Explained',
          type: 'article',
          duration: '5 min read',
          isCompleted: false,
          content: 'In this lesson, we cover the fundamental principles that will guide your journey. Understanding these core concepts is crucial for mastering the advanced topics later in the curriculum. We will explore the history, the theory, and the practical applications.'
        },
        {
          id: 'l3',
          title: 'Knowledge Check',
          type: 'quiz',
          duration: '5 questions',
          isCompleted: false,
          questions: [
            {
              id: 'q1',
              text: 'What is the primary benefit of the "Sage" color palette in UI design?',
              options: ['It induces anxiety', 'It promotes calmness and focus', 'It is the most popular color', 'It is invisible'],
              correctAnswer: 1
            },
            {
              id: 'q2',
              text: 'Which of the following is a key principle of minimal design?',
              options: ['Maximum clutter', 'Negative space', 'Using 10 different fonts', 'Blinking text'],
              correctAnswer: 1
            },
             {
              id: 'q3',
              text: 'In the context of this app, what does the "PixelBlast" component do?',
              options: ['Plays music', 'Renders a 3D particle background', 'Deletes data', 'Send emails'],
              correctAnswer: 1
            }
          ]
        }
      ]
    },
    {
      id: 'm2',
      title: 'Module 2: Advanced Techniques',
      lessons: [
         {
          id: 'l4',
          title: 'Mastering the Workflow',
          type: 'video',
          duration: '15:30',
          isCompleted: false,
          videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
        },
        {
          id: 'l5',
          title: 'Case Studies',
          type: 'article',
          duration: '10 min read',
          isCompleted: false
        }
      ]
    }
  ];

export const REVIEWS_SNIPPETS = [
  {
    id: 1,
    user: "Alex Johnson",
    role: "Frontend Developer",
    text: "Lumina changed my career trajectory. The React course was the bridge I needed to land a senior role.",
    avatar: "https://picsum.photos/100/100?random=20"
  },
  {
    id: 2,
    user: "Maria Rodriguez",
    role: "Product Designer",
    text: "The quality of instruction here is unmatched. It's not just theory; it's practical, industry-standard knowledge.",
    avatar: "https://picsum.photos/100/100?random=21"
  },
  {
    id: 3,
    user: "David Kim",
    role: "Data Analyst",
    text: "Concise, deep, and rigorous. Exactly what I was looking for to upskill without wasting time.",
    avatar: "https://picsum.photos/100/100?random=22"
  }
];